---
include:
- "**/*.rb"
exclude:
- bin/**/*
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
- Gemfile.lock
require: []
domains: []
reporters:
- rubocop
- require_not_found
require_paths: []
max_files: 5000
